# ETAP 1: Budowanie binarki natywnej
# Używamy oficjalnego obrazu GraalVM, który jest gotowy do pracy
FROM ghcr.io/graalvm/native-image-community:21 AS build

# Kopiujemy projekt
COPY . /home/app
WORKDIR /home/app

# Nadajemy uprawnienia i instalujemy brakujące narzędzia (findutils zawiera xargs)
# Na Renderze sieć powinna działać bez problemu, więc to przejdzie
RUN microdnf install -y findutils && chmod +x gradlew

# Kluczowy moment: Budowanie obrazu natywnego
# To potrwa kilka minut, Render da Ci znać w logach
RUN ./gradlew nativeCompile --no-daemon -x test

# ETAP 2: Uruchamianie (Lekki obraz bez Javy!)
FROM ubuntu:jammy
WORKDIR /app

# Kopiujemy gotową binarkę.
# UWAGA: Upewnij się, że nazwa 'nazwisko-app' zgadza się z nazwą Twojego projektu w settings.gradle
COPY --from=build /home/app/build/native/nativeCompile/nazwisko-app /app/server

# Render wymaga wystawienia portu
EXPOSE 8080

# Uruchamiamy bezpośrednio binarkę
ENTRYPOINT ["/app/server"]