datasources.default.password=wMse0riiK4O5z6V7gdcv86QePEPkNzZB
datasources.default.username=micronaut
datasources.default.url=jdbc:postgresql://dpg-d6h9ra0gjchc73ck8o80-a/micronaut_lr9f/micronaut_lr9f

